language: node_js
node_js:
  - "8"

install:
  - npm install
  - npm install -g mocha

env:
  - Test_dir= ./test/

script: npm run test
 
deploy:
  provider: heroku
  app : dispcar
  api_key:
    secure: 2988dfd5-cf14-4875-a4dd-74dc9c8fad16
  strategy: git 
  run: "npm run production"